name: background_fetch
description: Periodic callbacks in the background for both iOS and Android.  Includes Android Headless implementation.
version: 0.5.3
homepage: https://github.com/transistorsoft/flutter_background_fetch

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.transistorsoft.flutter.backgroundfetch
        pluginClass: BackgroundFetchPlugin
      ios:
        pluginClass: BackgroundFetchPlugin

